apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbGtvbCIsInBhc3N3b3JkIjoiZGNrcl9wYXRfZ1dpdlZSS2t4X3dBUUluaVZiR3hLOWVMbFZzIiwiYXV0aCI6IllXeHJiMnc2WkdOcmNsOXdZWFJmWjFkcGRsWlNTMnQ0WDNkQlVVbHVhVlppUjNoTE9XVk1iRlp6In19fQ==
kind: Secret
metadata:
  name: registry-secret-for-alkol
type: kubernetes.io/dockerconfigjson