---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-svc
spec:
  type: NodePort
  selector:
    server: mosquitto
  ports:
  - name: mqtt-notls-access
    port: 1883
    nodePort: 31883
    targetPort: mqtt-notls
  - name: mqtt-websocket-access
    port: 9001
    nodePort: 31885
    targetPort: mqtt-ws
