apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  securityContext:
    runAsUser: 999
    runAsGroup: 999
  containers:
    - name: mongo
      image: docker.io/mongo:7
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
  volumes:
    - name: mongo-vol
      persistentVolumeClaim:
        claimName: mongo-pvc-nfs