apiVersion: v1
kind: Namespace
metadata:
  name: mongo-sts-test
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-hostpath
  namespace: mongo-sts-test
provisioner: kubernetes.io/no-provisioner # Indicates manual PV creation
volumeBindingMode: WaitForFirstConsumer 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-1
  namespace: mongo-sts-test
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
  hostPath:
    path: /mnt/data
    type: "DirectoryOrCreate"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-2-192-168-1-242 # Replace with exact k8s node name at "kubectl get nodes" NAME column
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-1
  namespace: mongo-sts-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual-hostpath
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-standalone
  namespace: mongo-sts-test
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: hostpath-pvc
        persistentVolumeClaim:
          claimName: hostpath-pvc-1

      initContainers:
      - name: volume-permission-fix
        image: docker.io/mongo:7
        command: 
        - sh  
        - -c
        - |
          chown 999:999 -R /data
          chmod 750 -R /data
        volumeMounts:
        - name: hostpath-pvc
          mountPath: /data/db
          subPath: mongodb-data
        - name: hostpath-pvc
          mountPath: /data/configdb
          subPath: mongodb-config
      containers:
      - name: mongo7
        securityContext:
          runAsGroup: 999
          runAsUser: 999
        image: docker.io/mongo:7
        ports:
        - containerPort: 27017
          name: mongodb-port
        volumeMounts:
        - name: hostpath-pvc
          mountPath: /data/db
          subPath: mongodb-data
        - name: hostpath-pvc
          mountPath: /data/configdb
          subPath: mongodb-config

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: mongo-sts-test
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - port: 27017
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongo-sts-test
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express-container
        image: docker.io/mongo-express:1.0.2-20-alpine3.19
        ports:
        - containerPort: 8081
        env:
        - name: "ME_CONFIG_MONGODB_URL"
          value: "mongodb://mongo-standalone-0.mongodb-headless.mongo-sts-test" # default quick login: admin/pass
--- 
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo-sts-test
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30082
---
