---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-1
  namespace: mongo-sts-test
spec:
  storageClassName: manual-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
