apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: {{ .Values.app.replica }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      imagePullSecrets:
      - name: "registry-secret-for-{{ .Values.repoUsername }}"
      containers:
      - name: "{{ .Values.app.name }}"
        image: "{{ .Values.app.image }}"
        imagePullPolicy: "{{ .Values.app.imgPullPolicy }}"
        env: 
          - name: MONGO_HOST
            value: "{{ .Values.db.name }}-sts-0.{{ .Values.db.name }}-headless.{{ .Values.namespace }}.svc.cluster.local"
          - name: MONGO_PORT
            value: "{{ .Values.dbServicePort }}"        
        ports:
        - containerPort: {{ .Values.appContainerPort }}
        volumeMounts:
        - name: mongo-secret
          mountPath: /secrets
      volumes:
      - name: mongo-secret
        secret:
          secretName: mongo-creds



