apiVersion: v1
kind: Secret
metadata:
  name: "registry-secret-for-{{ .Values.repoUsername }}"
  namespace: "{{ .Values.namespace }}" 
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.registryAddr }}": {
          "username": "{{ .Values.repoUsername }}",
          "password": "{{ .Values.repoPersonalAccessToken }}",
          "auth": "{{ printf "%s:%s" .Values.repoUsername .Values.repoPersonalAccessToken | b64enc }}"
        }
      }
    }
