# Security was not mainly concernd at this point. 
# For AWS case, using Secret Manager service or EKS Pod Identity would be some production grade solutions.
apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: "{{ .Values.namespace }}" 
stringData:
  mongo-root: "{{ .Values.db.rootUser }}"
  mongo-pass: "{{ .Values.db.rootPass }}"
