apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: "{{ .Values.app.name }}-tg-config"
  namespace: "{{ .Values.namespace }}" 
spec:
  targetReference:
    name: "{{ .Values.app.name }}" # app' service name that httpRoute use as backendRef
  defaultConfiguration:
    targetType: ip # Pod IPs are ALB's target. Other ootion is "instance" which targets ec2 instances. Services should be set to NodePort